<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MNHcC\Module'                                => __DIR__ . '/Module.php',
    'MNHcC\Helper\DynamicCoder'                   => __DIR__ . '/src/MNHcC/Helper/DynamicCoder.php',
    'MNHcC\Helper\ObjectHelper'                   => __DIR__ . '/src/MNHcC/Helper/ObjectHelper.php',
    'MNHcC\Module\BasicModule'                    => __DIR__ . '/src/MNHcC/Module/BasicModule.php',
    'MNHcC\Router\Http\ExistingControllerSegment' => __DIR__ . '/src/MNHcC/Router/Http/ExistingControllerSegment.php',
    'MNHcC\Router\Http\SeoRouteMatch'             => __DIR__ . '/src/MNHcC/Router/Http/SeoRouteMatch.php',
    'MNHcC\Router\Http\SeoSegment'                => __DIR__ . '/src/MNHcC/Router/Http/SeoSegment.php',
);
