<?php
// Generated by MNHcC\Zend3bcHelper's ./bin/classmap_generator.php
return [
    'MNHcC\ExtendedZendRoutes\Router\Http\RouteMatch'            => __DIR__ . '/MNHcC/ExtendedZendRoutes/Router/Http/RouteMatch.php',
    'MNHcC\ExtendedZendRoutes\Router\Http\RouteInvokableFactory' => __DIR__ . '/MNHcC/ExtendedZendRoutes/Router/Http/RouteInvokableFactory.php',
    'MNHcC\ExtendedZendRoutes\Router\Http\Segment'               => __DIR__ . '/MNHcC/ExtendedZendRoutes/Router/Http/Segment.php',
];
