<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MNHcC\Router\Http\RouteMatch'            => __DIR__ . '/Router/Http/RouteMatch.php',
    'MNHcC\Router\Http\RouteInvokableFactory' => __DIR__ . '/Router/Http/RouteInvokableFactory.php',
    'MNHcC\Router\Http\Segment'               => __DIR__ . '/Router/Http/Segment.php',
);
