<?php
// Generated by MNHcC\Zend3bcHelper's mnhcc_classmap_generator.php (forked from Zend Framework 2) on 2016-09-05 20:01:20

return [
    \MNHcC\ExtendedZendRoutes\Router\Http\RouteMatch::class       => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'RouteMatch.php',
    \MNHcC\ExtendedZendRoutes\Router\Http\Segment::class                       => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'Segment.php',
    \MNHcC\ExtendedZendRoutes\Router\BaseRouteInvokableFactory::class          => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'BaseRouteInvokableFactory.php',
    \MNHcC\ExtendedZendRoutes\Router\Exception\ExceptionInterface::class       => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'ExceptionInterface.php',
    \MNHcC\ExtendedZendRoutes\Router\Exception\InvalidArgumentException::class => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'InvalidArgumentException.php',
    \MNHcC\ExtendedZendRoutes\Router\Exception\RuntimeException::class         => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'RuntimeException.php',
];
