<?php
// Generated by MNHcC\Zend3bcHelper's mnhcc_classmap_generator.php (forked from Zend Framework 2) on 2016-08-26 23:53:38

return [
    \MNHcC\ExtendedZendRoutes\Router\Http\RouteInvokableFactory::class => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'RouteInvokableFactory.php',
    \MNHcC\ExtendedZendRoutes\Router\Http\RouteMatch::class                         => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'RouteMatch.php',
    \MNHcC\ExtendedZendRoutes\Router\Http\Segment::class                            => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'Segment.php',
];
