<?php
// Generated by MNHcC\Zend3bcHelper's ./bin/classmap_generator.php
return [
    'MNHcC\ExtendedZendRoutes\Router\Http\ExistingControllerSegment' => __DIR__ . '/MNHcC/ExtendedZendRoutes/Router/Http/ExistingControllerSegment.php',
    'MNHcC\ExtendedZendRoutes\Router\Http\SeoSegment'                => __DIR__ . '/MNHcC/ExtendedZendRoutes/Router/Http/SeoSegment.php',
    'MNHcC\ExtendedZendRoutes\Router\Http\SeoRouteMatch'             => __DIR__ . '/MNHcC/ExtendedZendRoutes/Router/Http/SeoRouteMatch.php',
    'MNHcC\ExtendedZendRoutes\Router\RouteInvokableFactory'          => __DIR__ . '/MNHcC/ExtendedZendRoutes/Router/RouteInvokableFactory.php',
    'MNHcC\ExtendedZendRoutes\Module'                                => __DIR__ . '/Module.php',
];
