<?php
// Generated by MNHcC\Zend3bcHelper's mnhcc_classmap_generator.php (forked from Zend Framework 2) on 2016-08-26 23:59:53

return [
    \MNHcC\ExtendedZendRoutes\Module::class                                => __DIR__ . DIRECTORY_SEPARATOR .'Module.php',
    \MNHcC\ExtendedZendRoutes\Router\Http\ExistingControllerSegment::class => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'ExistingControllerSegment.php',
    \MNHcC\ExtendedZendRoutes\Router\Http\SeoRouteMatch::class             => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'SeoRouteMatch.php',
    \MNHcC\ExtendedZendRoutes\Router\Http\SeoSegment::class                => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'Http' . DIRECTORY_SEPARATOR . 'SeoSegment.php',
    \MNHcC\ExtendedZendRoutes\Router\RouteInvokableFactory::class          => __DIR__ . DIRECTORY_SEPARATOR .'Router' . DIRECTORY_SEPARATOR . 'RouteInvokableFactory.php',
];
